Repository SpaiR/StrongDMM, pull requests merged in 2023-07, with the labels that each got.

#211 Ensures whitespace inside text in list pops isn't duplicated
  internal/dmapi/dmmap/dmmdata/parse.go
  internal/dmapi/dmmap/dmmdata/parse_test.go
Labels: fix

#220 Find on Map searches by path
  internal/app/ui/cpenvironment/environment.go
  internal/app/ui/cpenvironment/menu.go
Labels: tweak, go

#217 Autocorrect unenclosed strings and lists
  internal/app/ui/cpvareditor/vareditor.go
Labels: enhancement, go

#218 adds the single move tool
  internal/app/ui/cpwsarea/wsmap/pmap/canvas_overlay.go
  internal/app/ui/cpwsarea/wsmap/pmap/panel_tools.go
  internal/app/ui/cpwsarea/wsmap/pmap/shortcut.go
  internal/app/ui/cpwsarea/wsmap/pmap/tools.go
  internal/app/ui/cpwsarea/wsmap/tools/move.go
  internal/app/ui/cpwsarea/wsmap/tools/tools.go
  internal/imguiext/icon/icon.go
  internal/rsc/font/icons/icomoon.svg
  internal/rsc/font/icons/icomoon.ttf
  internal/rsc/font/icons/icomoon.woff
  internal/rsc/font/icons/selection.json
Labels: enhancement, go

#219 Adds border-fill to the border fill tool
  internal/app/ui/cpwsarea/wsmap/pmap/panel_tools.go
  internal/app/ui/cpwsarea/wsmap/tools/fill.go
Labels: enhancement, go

#216 Adds "Screenshot in Selection" checkbox to screenshot tool
  internal/app/ui/cpwsarea/wsmap/pmap/psettings/screenshot.go
Labels: enhancement, go

#221 updates changelog
  CHANGELOG.md
Labels: documentation

#222 fixes a single move tool crash bug
  internal/app/ui/cpwsarea/wsmap/tools/move.go
Labels: fix, go
