Repository SpaiR/StrongDMM, pull requests merged in 2024-11, with the labels that each got.

#321 Fix dir being ignored in preview for nodes
  internal/app/ui/cpenvironment/node.go
Labels: enhancement

#324 Handling for the parser errors
  internal/app/project.go
  internal/dmapi/dmenv/dme.go
  third_party/sdmmparser/sdmmparser.go
  third_party/sdmmparser/src/environment.rs
  third_party/sdmmparser/src/icon.rs
Labels: feat

#325 More precise rust target handling
  .github/workflows/ci.yml
  Taskfile.yml
Labels: chore
