Repository SpaiR/StrongDMM, pull requests merged in 2024-07, with the labels that each got.

#286 adds pixel drag mode to move tool
  internal/app/ui/cpwsarea/wsmap/pmap/editor/editor.go
  internal/app/ui/cpwsarea/wsmap/pmap/panel_tools.go
  internal/app/ui/cpwsarea/wsmap/tools/move.go
  internal/app/ui/cpwsarea/wsmap/tools/tools.go
Labels: enhancement

#294 up: bump SpacemandDMM and other rust deps
  .github/workflows/ci.yml
  .golangci.yml
  README.md
  go.mod
  go.sum
  internal/rsc/txt/about.txt
  third_party/sdmmparser/sdmmparser.go
  third_party/sdmmparser/src/Cargo.lock
  third_party/sdmmparser/src/Cargo.toml
  third_party/sdmmparser/src/lib.rs
Labels: dependencies, rust, github_actions

#295 Trims off effect layers, makes rendering a bit more sane
  internal/app/render/bucket/level/chunk/unit/unit.go
Labels: fix
